site_name: Competitive Coding AI
site_description: End-to-end pipeline for SFT, generation, and evaluation of competitive programming solutions
repo_url: https://github.com/erranlli/competitive-coding-ai
docs_dir: docs
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Datasets: datasets.md
  - Training: training.md
  - Inference: inference.md
  - Evaluation: evaluation.md
  - Data Utilities: data_util.md
  - Benchmarks: benchmarks.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
